const products = [
  {
    title: "Ford F-150 Headlight Assembly",
    category: "Motors",
    images_url:["https://m.media-amazon.com/images/I/815Rf7rHt+L._AC_SX466_PIbundle-2,TopRight,0,0_SH20_.jpg"],
    description: "OEM or aftermarket unit, fits 2015–2020 Ford F-150. Clear lens, tested and functional. Minor surface wear possible.",
    price: 14000,
    quantity: 4,
    condition: "Refurbished",
    year_of_manufacture: 2002,
    brand: "Ford",
    model: "Model-309",
    dimensions: {
      length: 5.77,
      width: 5.83,
      height: 74.11
    },
    weight: 26.55,
    material: "Polycarbonate lens, metal/plastic housing",
    color: "Black",
    original_packaging: true,
    manual_included: false,
    working_condition: "Works with minor issues"
  },
  {
    title: "Dell XPS 13 Laptop",
    category: "Electronics",
    images_url:["hhttps://cdn.mos.cms.futurecdn.net/kMkWVRBsjVw3MnbxBUM9pj-1920-80.jpg.webpttps://www.techradar.com/computing/windows-laptops/dell-xps-13-intel-core-ultra-2nd-gen-2025-review"],
    description: "Dell XPS 13, Intel i5/i7, 8GB RAM, 256GB SSD. 13.3' display, slim, lightweight, Windows 11. Light scratches, battery replaced if older.",
    price: 45000,
    quantity: 8,
    condition: "Refurbished",
    year_of_manufacture: null,
    brand: "Dell",
    model: "Model-733",
    dimensions: { length: 40.46, width: 79.21, height: 5.07 },
    weight: 15.71,
    material: "Aluminum chassis, Gorilla Glass screen",
    color: "Red",
    original_packaging: false,
    manual_included: true,
    working_condition: "Lightly used, good condition"
  },
  {
    title: "Coach Leather Handbag",
    category: "Clothing & Accessories",
    images_url:["https://cdn.pixabay.com/photo/2017/08/07/00/27/purse-2597948_1280.jpg"],
    description: "The Coach Women's hand bag C4084 IMF2L MOLLIE TOTE 25 is a stylish and versatile shoulder bag perfect for casual occasions. Made with white leather exterior, gold hardware accents, and adjustable white leather straps, this small rectangular bag features a zip closure and double handles with a 4.75-inch drop.",
    price: 834.41,
    quantity: 15,
    condition: "Used - Like New",
    year_of_manufacture: null,
    brand: "Coach",
    model: "C4084 IMF2L MOLLIE TOTE 25",
    dimensions: { length: 63.12, width: 42.9, height: 98.99 },
    weight: 29.89,
    material: "Leather",
    color: "White",
    original_packaging: true,
    manual_included: true,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Restaurant Grade Espresso Machine",
    category: "Business & Industrial",
    images_url:["https://m.media-amazon.com/images/I/71pm5UidpUL._AC_SX679_.jpg"],
    description: "2-group head, semi-automatic. Serviced, includes portafilter and accessories.",
    price: 35000,
    quantity: 11,
    condition: "New",
    year_of_manufacture: 2004,
    brand: "Restaurant",
    model: "Model-282",
    dimensions: { length: 58.03, width: 22.81, height: 40.59 },
    weight: 12.62,
    material: "Stainless steel, brass internals",
    color: "Gray",
    original_packaging: false,
    manual_included: false,
    working_condition: "Requires repair"
  },
  {
    title: "Dyson V11 Vacuum Cleaner",
    category: "Home & Garden",
    images_url:["https://cdn.mos.cms.futurecdn.net/M6hh2ft35gHMKAnEZBfFGZ-1920-80.jpg.webp"],
    description: "Cordless stick vacuum, all accessories included. Filter cleaned, well-maintained, minor scratches from use.",
    price: 20000,
    quantity: 1,
    condition: "Used - Like New",
    year_of_manufacture: 2006,
    brand: "Dyson",
    model: "Model-521",
    dimensions: { length: 51.72, width: 74.34, height: 19.08 },
    weight: 19.38,
    material: "ABS plastic, stainless steel",
    color: "Red",
    original_packaging: false,
    manual_included: true,
    working_condition: "Lightly used, good condition"
  },
  {
    title: "Wilson Tennis Racket",
    category: "Sporting Goods",
    images_url:["https://images.unsplash.com/photo-1560012057-4372e14c5085?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHRlbm5pcyUyMHJhY2tldHxlbnwwfHwwfHx8MA%3D%3D"],
    description: "Strung, grip replaced. Some paint chips, structurally solid, includes cover.",
    price: 7000,
    quantity: 9,
    condition: "Used - Like New",
    year_of_manufacture: null,
    brand: "Wilson",
    model: "Model-993",
    dimensions: { length: 55.63, width: 58.2, height: 9.92 },
    weight: 17.08,
    material: "Graphite composite",
    color: "Yellow",
    original_packaging: true,
    manual_included: false,
    working_condition: "Lightly used, good condition"
  },
  {
    title: "Seiko 5 Automatic Watch",
    category: "Jewelry & Watches",
    images_url:["https://www.watchportal.com.ph/cdn/shop/files/seiko-snk615k1-automatic-silver-stainless-steel-watch-for-men-watchportal-ph.jpg?v=1697124541&width=400"],
    description: "38mm case, mechanical movement. Few surface scratches, runs accurately.",
    price: 8000,
    quantity: 8,
    condition: "Refurbished",
    year_of_manufacture: 1998,
    brand: "Seiko",
    model: "Model-230",
    dimensions: { length: 50.92, width: 31.43, height: 51.52 },
    weight: 10.11,
    material: "Stainless steel",
    color: "Red",
    original_packaging: false,
    manual_included: false,
    working_condition: "Works with minor issues"
  },
  {
    title: "Pokemon Charizard Holo Card (1st Edition)",
    category: "Collectibles & Art",
    images_url:["https://beckett-www.s3.amazonaws.com/news/news-content/uploads/2017/08/1999-Pokemon-Game-1st-Edition-Holo-Charizard-BGS-10-PWCC-Aug-2017-Front.jpg"],
    description: "Original, lightly played, holographic finish. Edges may show minor wear.",
    price: 9000,
    quantity: 10,
    condition: "Used - Like New",
    year_of_manufacture: null,
    brand: "Pokemon",
    model: "Model-501",
    dimensions: { length: 27.4, width: 96.61, height: 21.16 },
    weight: 18.18,
    material: "Printed card stock",
    color: "Red",
    original_packaging: false,
    manual_included: false,
    working_condition: "Lightly used, good condition"
  },
  {
    title: "Johnson's Baby Shampoo",
    category: "Other Categories",
    images_url:["https://images.ctfassets.net/aub2fvcyp2t8/39tZXffnAfykKscf9zj3o2/15b26ae4328b9a8b6065ea78490bb1f5/nmt_image_1_new-hi-in?fm=webp&w=1024"],
    description: "500ml, sealed, recent manufacturing date, expiry verified.",
    price: 150,
    quantity: 16,
    condition: "New",
    year_of_manufacture: null,
    brand: "Johnson's",
    model: "Model-944",
    dimensions: { length: 92.79, width: 60.6, height: 58.24 },
    weight: 1.71,
    material: "Plastic bottle (contents: shampoo liquid)",
    color: "Gray",
    original_packaging: false,
    manual_included: true,
    working_condition: "New"
  },
    {
    title: "BMW 3 Series Alloy Wheel",
    category: "Motors",
    images_url:["https://route66dublin.ie/wp-content/uploads/2023/05/20230325_082519_1683972059.jpg"],
    description: "Genuine BMW, 17' diameter. Minor scratches, not bent, clean hub.",
    price: 20000,
    quantity: 10,
    condition: "Used - Good",
    year_of_manufacture: null,
    brand: "BMW",
    model: "Model-884",
    dimensions: { length: 82.72, width: 37.92, height: 40.98 },
    weight: 24.77,
    material: "Aluminum alloy",
    color: "Black",
    original_packaging: false,
    manual_included: true,
    working_condition: "Fully functional"
  },
  {
    title: "Sony PlayStation 5 Console",
    category: "Electronics",
    images_url:["https://wallpapers.com/images/high/ps5-pictures-59ev5t1kpebtafu1.webp"],
    description: "PS5 Disc Edition, with controller, cables, and original box. Minor marks, fully functional.",
    price: 50000,
    quantity: 10,
    condition: "New",
    year_of_manufacture: 2005,
    brand: "Sony",
    model: "Model-864",
    dimensions: { length: 96.42, width: 50.12, height: 31.74 },
    weight: 9.78,
    material: "Plastic shell, electronic components",
    color: "White",
    original_packaging: false,
    manual_included: true,
    working_condition: "Fully functional"
  },
  {
    title: "Adidas Ultraboost Running Shoes (UK 9)",
    category: "Clothing & Accessories",
    images_url:["https://www.solereview.com/wp-content/uploads/2022/01/adidas_Ultraboost_22_side-view.jpg"],
    description: "UK size 9. Clean, no major sole wear.",
    price: 7500,
    quantity: 1,
    condition: "Used - Good",
    year_of_manufacture: 2008,
    brand: "Adidas",
    model: "Model-889",
    dimensions: { length: 59.09, width: 61.5, height: 12.29 },
    weight: 16.93,
    material: "Knit textile upper, rubber sole",
    color: "Blue",
    original_packaging: false,
    manual_included: false,
    working_condition: "Fully functional"
  },
  {
    title: "Restaurant Grade Espresso Machine",
    category: "Business & Industrial",
    images_url:["https://m.media-amazon.com/images/I/71e4PRs5sWL.__AC_SX300_SY300_QL70_FMwebp_.jpg"],
    description: "2-group head, semi-automatic. Serviced, includes portafilter and accessories.",
    price: 50000,
    quantity: 3,
    condition: "Used - Good",
    year_of_manufacture: 2022,
    brand: "Restaurant",
    model: "Model-438",
    dimensions: { length: 68.77, width: 55.87, height: 49.31 },
    weight: 28.29,
    material: "Stainless steel, brass internals",
    color: "Silver",
    original_packaging: false,
    manual_included: true,
    working_condition: "Requires repair"
  },
  {
    title: "Char-Broil Gas Grill",
    category: "Home & Garden",
    images_url:["https://m.media-amazon.com/images/I/515zbq8lNjL._AC_SX679_.jpg"],
    description: "4 burners, ignition system working. Grease tray cleaned, includes cover.",
    price: 20000,
    quantity: 1,
    condition: "Used - Like New",
    year_of_manufacture: 2019,
    brand: "Char-Broil",
    model: "Model-886",
    dimensions: { length: 12.41, width: 63.51, height: 64.07 },
    weight: 19.55,
    material: "Stainless steel frame, cast iron grates",
    color: "White",
    original_packaging: true,
    manual_included: false,
    working_condition: "Works with minor issues"
  },
  {
    title: "Wilson Tennis Racket",
    category: "Sporting Goods",
    images_url:["https://images.unsplash.com/photo-1560012057-4372e14c5085?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHRlbm5pcyUyMHJhY2tldHxlbnwwfHwwfHx8MA%3D%3D"],
    description: "Strung, grip replaced. Some paint chips, structurally solid, includes cover.",
    price: 6000,
    quantity: 2,
    condition: "Used - Like New",
    year_of_manufacture: null,
    brand: "Wilson",
    model: "Model-452",
    dimensions: { length: 14.48, width: 17.57, height: 59.69 },
    weight: 25.75,
    material: "Graphite composite",
    color: "Green",
    original_packaging: false,
    manual_included: false,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Pandora Silver Charm Bracelet",
    category: "Jewelry & Watches",
    images_url:["https://i.etsystatic.com/58017865/r/il/b0873c/7129807215/il_1588xN.7129807215_580k.jpg"],
    description: "19cm, semi-polished, minor wear.",
    price: 5000,
    quantity: 5,
    condition: "Used - Good",
    year_of_manufacture: null,
    brand: "Pandora",
    model: "Model-948",
    dimensions: { length: 84.14, width: 77.8, height: 41.3 },
    weight: 4.17,
    material: "Sterling silver",
    color: "Silver,Rosegold,Gold",
    original_packaging: true,
    manual_included: true,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Rare US Silver Dollar 1921",
    category: "Collectibles & Art",
    images_url:["https://i.etsystatic.com/22659270/c/2062/2062/517/346/il/4f6f97/7163993156/il_600x600.7163993156_iwhw.jpg"],
    description: "Morgan, circulated. Visible details, modest wear, not cleaned.",
    price: 11000,
    quantity: 7,
    condition: "Used - Like New",
    year_of_manufacture: 2006,
    brand: "Rare",
    model: "Model-562",
    dimensions: { length: 57.96, width: 33.87, height: 70.34 },
    weight: 2.8,
    material: "90% silver",
    color: "Black",
    original_packaging: false,
    manual_included: true,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Acoustic Guitar Yamaha F310",
    category: "Other Categories",
    images_url:["https://images.musicstore.de/images/0640/yamaha-f310-acoustic-guitar_1_GIT0000613-001.jpg"],
    description: "Reliable, full-sized acoustic guitar ideal for beginners and intermediate players. Features a spruce top for a bright, resonant tone and rosewood fingerboard for smooth playability. Slightly reduced body depth for comfortable handling. Known for excellent intonation and durability. Typically sold without a case or stand",
    price: 7000,
    quantity: 18,
    condition: "New",
    year_of_manufacture: 2007,
    brand: "Acoustic",
    model: "Model-193",
    dimensions: { length: 92.12, width: 59.26, height: 81.8 },
    weight: 28.58,
    material: "Top: Spruce, Back & Sides: Meranti or locally sourced tonewood, Neck: Nato or similar tonewood, Fingerboard: Rosewood, Bridge: Rosewood, Hardware: Chrome-plated tuners.",
    color: "White",
    original_packaging: false,
    manual_included: false,
    working_condition: "Excellent condition, almost new"
  },
  {
  title: "Ray-Ban Wayfarer Sunglasses",
  category: "Accessories",
  images_url: ["https://img.ebdcdn.com/product/frame/gray/luspl00477_0.jpg?q=85&im=Resize,width=640,height=320,aspect=fill;UnsharpMask,sigma=1.0,gain=1.0"],
  description: "Classic Ray-Ban Wayfarer sunglasses. Iconic design with durable acetate frame and UV-protective lenses. Slight scratches on frame, lenses immaculate.",
  price: 5200,
  quantity: 8,
  condition: "Used - Good",
  year_of_manufacture: 2021,
  brand: "Ray-Ban",
  model: "Wayfarer RB2140",
  dimensions: { lens_width_mm: 50, bridge_width_mm: 22, arm_length_mm: 150 },
  weight: 0.15,
  material: "Acetate frame, glass lenses",
  color: "Black",
  original_packaging: false,
  manual_included: false,
  working_condition: "Fully functional"
} ,
  {
    title: "Apple iPhone 13 Pro Max (128GB)",
    category: "Electronics",
    images_url:["https://www.att.com/scmsassets/global/devices/phones/apple/apple-iphone-13-pro-max/Carousel/alpinegreen/AlpineGreen-1.png"],
    description: "128GB, unlocked, box and charger. Display clean, battery health over 85%.",
    price: 70000,
    quantity: 1,
    condition: "Refurbished",
    year_of_manufacture: 2008,
    brand: "Apple",
    model: "Model-752",
    dimensions: { length: 75.96, width: 34.78, height: 24.29 },
    weight: 24.9,
    material: "Stainless steel frame, glass back",
    color: "Green",
    original_packaging: true,
    manual_included: false,
    working_condition: "Fully functional"
  },
  {
    title: "Nike Air Jordan 1 Retro High OG",
    category: "Clothing & Accessories",
    images_url:["https://http2.mlstatic.com/D_NQ_NP_2X_771065-MLM91424575331_092025-F.webp"],
    description: "US size 10. Collector’s model, minimal creasing, original box if available.",
    price: 27000,
    quantity: 7,
    condition: "New",
    year_of_manufacture: null,
    brand: "Nike",
    model: "Model-351",
    dimensions: { length: 97.96, width: 61.17, height: 23.5 },
    weight: 1.85,
    material: "Leather upper, rubber outsole",
    color: "Brown",
    original_packaging: false,
    manual_included: false,
    working_condition: "Works with minor issues"
  },
  {
  title: "Bosch PS31-2A 12V Max 3/8 Inch Drill/Driver Kit",
  category: "Business & Industrial",
  images_url: ["hhttps://www.acmetools.com/dw/image/v2/BHBS_PRD/on/demandware.static/-/Sites-acme-catalog-m-en/default/dwc0716aa4/images/images/catalog/product/000346441055/bosch-12v-max-38-inch-drill-driver-kit-ps31-2a.jpg?sw=380"],
  description: "Bosch PS31-2A 12V Max cordless drill/driver kit, includes (2) 2Ah batteries, charger, and carrying case. Lightweight, variable speed, and ideal for DIY tasks or professional use.",
  price: 9500,
  quantity: 10,
  condition: "Used - Like New",
  year_of_manufacture: 2022,
  brand: "Bosch",
  model: "PS31-2A",
  dimensions: { length: 20, width: 6.1, height: 17.7 }, 
  weight: 1,
  material: "Composite plastic, metal gears",
  color: "Blue/Black/Red",
  original_packaging: true,
  manual_included: true,
  working_condition: "Fully functional"
},
  {
    title: "IKEA Wooden Dining Table",
    category: "Home & Garden",
    images_url:["https://www.ikea.com/us/en/images/products/haegernaes-table-and-4-chairs-antique-stain-pine__1350925_pe951817_s5.jpg?f=xl"],
    description: "180x90cm, 4-seater, light stains, legs sturdy, minimal wobble.",
    price: 9000,
    quantity: 8,
    condition: "Used - Like New",
    year_of_manufacture: null,
    brand: "IKEA",
    model: "Model-804",
    dimensions: { length: 84.62, width: 29.72, height: 37.93 },
    weight: 7.32,
    material: "Solid pine or oak",
    color: "Brown",
    original_packaging: true,
    manual_included: false,
    working_condition: "Fully functional"
  },
  {
    title: "Callaway Golf Driver (Epic Flash, Regular Flex)",
    category: "Sporting Goods",
    images_url:["https://cdn.shopify.com/s/files/1/0559/0450/1875/files/epic.jpg?v=1738159077"],
    description: "Standard loft, regular flex shaft. Clubface clean, minor scuffs.",
    price: 12000,
    quantity: 13,
    condition: "Used - Good",
    year_of_manufacture: null,
    brand: "Callaway",
    model: "Model-402",
    dimensions: { length: 6.76, width: 54.61, height: 70.74 },
    weight: 28.66,
    material: "Titanium/graphite",
    color: "Green",
    original_packaging: true,
    manual_included: true,
    working_condition: "Lightly used, good condition"
  },
  {
    title: "Tiffany & Co. Diamond Ring",
    category: "Jewelry & Watches",
    images_url:["https://di2ponv0v5otw.cloudfront.net/posts/2025/09/05/68bbb74da255405e5c698252/m_wp_68bbb751c71ba131b69fe6c3.webp"],
    description: "Classic solitaire, certified. Size 6.5 (US), includes box and papers.",
    price: 85000,
    quantity: 4,
    condition: "Used - Like New",
    year_of_manufacture: 2010,
    brand: "Tiffany",
    model: null,
    dimensions: { length: 68.23, width: 95.85, height: 47.76 },
    weight: 13.15,
    material: "Platinum/white gold, diamond",
    color: "Silver",
    original_packaging: true,
    manual_included: false,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Vintage Star Wars Action Figure",
    category: "Collectibles & Art",
    images_url:["https://m.media-amazon.com/images/I/7102FwKRfAS.__AC_SX300_SY300_QL70_FMwebp_.jpg"],
    description: "Figures, includes original accessories. Limbs tight, paint mostly intact.",
    price: 9000,
    quantity: 7,
    condition: "New",
    year_of_manufacture: null,
    brand: "Vintage",
    model: "Model-983",
    dimensions: { length: 39.69, width: 18.84, height: 56.95 },
    weight: 13.32,
    material: "Plastic",
    color: "Green",
    original_packaging: false,
    manual_included: true,
    working_condition: "Fully functional"
  },
  {
    title: "Olay Regenerist Face Cream",
    category: "Home and Lifestyle",
    images_url:["https://www.nanamall.com/cdn/shop/files/olay-regenerist-micro-sculpting-cream-50g-416214.jpg?v=1750064836&width=800"],
    description: "50g, sealed, batch date visible, genuine product.",
    price: 900,
    quantity: 14,
    condition: "Used - Good",
    year_of_manufacture: 2008,
    brand: "Olay",
    model: "Model-536",
    dimensions: { length: 44.48, width: 7.29, height: 13.82 },
    weight: 18.93,
    material: "Plastic jar, cream contents",
    color: "Blue",
    original_packaging: false,
    manual_included: false,
    working_condition: "Sealed"
  },
  {
  title: "Disney Tsum Tsum Plush (Mickey Mouse)",
  category: "Toys & Collectibles",
  images_url: ["https://i.ebayimg.com/images/g/V2QAAOSwIABcQ7Tl/s-l960.webp"],
  description: "Official Disney Tsum Tsum Minnie Mouse plush. Super soft, stackable, and irresistibly cute—perfect for any toy collection or as a desk buddy.",
  price: 650,
  quantity: 10,
  condition: "Used - Like New",
  year_of_manufacture: 2021,
  brand: "Disney",
  model: "Tsum Tsum",
  dimensions: { length: 9, width: 6, height: 5 },
  weight: 0.08,
  material: "Plush fabric, polyester stuffing",
  color: "Black/Red/White",
  original_packaging: false,
  manual_included: false,
  working_condition: "Like new, clean and cuddly"
},
  {
    title: "Samsung Galaxy Watch 5",
    category: "Electronics",
    images_url:["https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch5.jpg"],
    description: "44mm Bluetooth model, charger included. Display scratch-free; band sanitized.",
    price: 13000,
    quantity: 17,
    condition: "Used - Like New",
    year_of_manufacture: 2002,
    brand: "Samsung",
    model: "Model-684",
    dimensions: { length: 95.02, width: 38.78, height: 21.06 },
    weight: 23.83,
    material: "Aluminum case, Gorilla Glass",
    color: "Blue",
    original_packaging: true,
    manual_included: false,
    working_condition: "Requires repair"
  },
  {
    title: "North Face Winter Jacket",
    category: "Clothing & Accessories",
    images_url:["https://m.media-amazon.com/images/I/61MVf0AxF9L._AC_SX679_.jpg"],
    description: "Men’s Large, hooded, insulated jacket. Minor wear, washed and clean.",
    price: 7500,
    quantity: 2,
    condition: "Refurbished",
    year_of_manufacture: 2011,
    brand: "North",
    model: null,
    dimensions: { length: 30.4, width: 48.53, height: 40.55 },
    weight: 9.11,
    material: "Nylon shell, synthetic insulation",
    color: "Black",
    original_packaging: false,
    manual_included: false,
    working_condition: null
  },
  {
    title: "Levi's Women's Jeans",
    category: "Women's Clothing",
    images_url:["https://resources.mandmdirect.com/Images/_default/l/v/3/lv33364_1_cloudzoom.jpg"],
    description: "Levi’s Women’s 712 Slim Fit Jeans in dark blue with classic five-pocket styling. Waist 28, Inseam 30 inches",
    price: 1800,
    quantity: 1,
    condition: "Used",
    year_of_manufacture: null,
    brand: "Levi's",
    model: "712 Slim",
    dimensions: { waist: 28, inseam: 30 },
    weight: 0.65,
    material: "98% Cotton, 2% Elastane",
    color: "Blue",
    original_packaging: false,
    manual_included: false,
    working_condition: "Ready to wear"
  },
  {
    title: "Philips Air Fryer XXL",
    category: "Home & Garden",
    images_url:["https://www.nellaonline.com/cdn/shop/products/HD965096img6_710x710.jpg?v=1661284640"],
    description: "Large capacity air fryer, 6–7L. All functions tested, basket cleaned, minimal cosmetic damage.",
    price: 9500,
    quantity: 12,
    condition: "New",
    year_of_manufacture: null,
    brand: "Philips",
    model: "Model-871",
    dimensions: { length: 98.47, width: 89.56, height: 34.88 },
    weight: 22.61,
    material: "Plastic housing, metal basket",
    color: "Black",
    original_packaging: false,
    manual_included: true,
    working_condition: "Requires repair"
  },
  {
    title: "Callaway Golf Driver",
    category: "Sporting Goods",
    images_url:["https://golfroots.com/cdn/shop/files/SMW7991_a4053f2c-6c2b-4d99-bb87-32132ecccf3a.jpg?v=1752224872&width=800"],
    description: "Standard loft, regular flex shaft. Clubface clean, minor scuffs.",
    price: 13500,
    quantity: 12,
    condition: "Used - Like New",
    year_of_manufacture: null,
    brand: "Callaway",
    model: "Model-298",
    dimensions: { length: 36.48, width: 97.55, height: 46.29 },
    weight: 27.27,
    material: "Titanium/graphite",
    color: "Gray",
    original_packaging: true,
    manual_included: false,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Rolex Submariner Watch",
    category: "Jewelry & Watches",
    images_url:["https://cdn.shopify.com/s/files/1/0278/9723/3501/files/Rolex-Submariner-original-1953-2_b9562e31-d954-474c-ad5b-eee9b1593562.jpg?v=1695136014"],
    description: "40mm case, with box and papers. Minimal wear, serviced recently.",
    price: 155000,
    quantity: 20,
    condition: "Used - Good",
    year_of_manufacture: null,
    brand: "Rolex",
    model: "Model-281",
    dimensions: { length: 81.86, width: 23.56, height: 44.56 },
    weight: 12.13,
    material: "Stainless steel",
    color: "Red",
    original_packaging: false,
    manual_included: true,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Michael Jordan Rookie Card",
    category: "Collectibles & Art",
    images_url:["https://m.media-amazon.com/images/I/61J5LM79RtL.__AC_SX342_SY445_QL70_FMwebp_.jpg"],
    description: "1986 Fleer #57, ungraded. Minor corner wear, no creases.",
    price: 2000,
    quantity: 3,
    condition: "Refurbished",
    year_of_manufacture: null,
    brand: "Michael",
    model: "Model-245",
    dimensions: { length: 59.31, width: 79.52, height: 72.92 },
    weight: 26.02,
    material: "Printed card stock",
    color: "Blue",
    original_packaging: true,
    manual_included: false,
    working_condition: "Fully functional"
  },
  {
    title: "LEGO Star Wars Millennium Falcon",
    category: "Other Categories",
    images_url:["https://i.etsystatic.com/10854630/r/il/f5b231/6705807980/il_1588xN.6705807980_pl63.jpg"],
    description: "1970s Kenner figure, includes original accessories. Limbs tight, paint mostly intact.",
    price: 18000,
    quantity: 8,
    condition: "Used - Good",
    year_of_manufacture: 1998,
    brand: "LEGO",
    model: "Model-697",
    dimensions: { length: 82.81, width: 31.09, height: 10.17 },
    weight: 22.95,
    material: "Plastic",
    color: "White",
    original_packaging: true,
    manual_included: false,
    working_condition: "Works with minor issues"
  },
  {
    title: "BMW 3 Series Alloy Wheel",
    category: "Motors",
    images_url:["https://www.bmautosport.co.uk/images/products/8243/24615/600x600/id-5739.jpg"],
    description: "Genuine BMW 3 Series 17-inch aluminum alloy wheel. Refurbished with light scuffs, structurally sound and ready for use.",
    price: 15000,
    quantity: 13,
    condition: "Refurbished",
    brand: "BMW",
    model: "Alloy Wheel 17-inch",
    dimensions: { diameter_inch: 17, width_inch: 7 },
    weight_kg: 6.98,
    material: "Aluminum alloy",
    color: "Silver",
    original_packaging: false,
    manual_included: false,
    working_condition: "Lightly used, good condition"
  },
  {
    title: "Samsung Galaxy Watch 5",
    category: "Electronics",
    images_url:["https://cdn.mos.cms.futurecdn.net/FoLJxAyGnyiu8JXUcvtvNE-1437-80.jpg.webp"],
    description: "Samsung Galaxy Watch 5, 44mm aluminum case with Gorilla Glass. Brand new condition, fully functional.",
    price: 15000,
    quantity: 6,
    condition: "New",
    brand: "Samsung",
    model: "Galaxy Watch 5 44mm",
    dimensions_mm: { length: 44, width: 38, height: 9.8 },
    weight_grams: 30,
    material: "Aluminum and glass",
    color: "Gray",
    original_packaging: true,
    manual_included: true,
    working_condition: "Excellent condition, almost new"
  },
  {
    title: "Coach Leather Handbag",
    category: "Clothing & Accessories",
    images_url:["https://coach.scene7.com/is/image/Coach/cp770_b4ydv_a0?$desktopProduct$"],
    description: "Authentic Coach leather handbag, medium size, brown color. New with minor cosmetic imperfections.",
    price: 10000,
    quantity: 18,
    condition: "New",
    brand: "Coach",
    model: "Signature Tote",
    dimensions_cm: { length: 30, width: 12, height: 25 },
    weight_kg: 1.5,
    material: "Genuine leather",
    color: "Brown",
    original_packaging: false,
    manual_included: false,
    working_condition: "Good condition"
  },
  {
    title: "Stainless Steel Commercial Kitchen Sink",
    category: "Business & Industrial",
    images_url:["https://m.media-amazon.com/images/I/71utqq9I2bL._AC_SX679_.jpg"],
    description: "Durable commercial-grade stainless steel double bowl kitchen sink, refurbished, excellent condition.",
    price: 12000,
    quantity: 19,
    condition: "Refurbished",
    brand: "Generic Stainless Steel",
    model: "Commercial Double Bowl Sink",
    dimensions_cm: { length: 180, width: 60, height: 50 },
    weight_kg: 25,
    material: "304 stainless steel",
    color: "Silver",
    original_packaging: false,
    manual_included: false,
    working_condition: "Excellent condition"
  },
  {
    title: "Dyson V11 Vacuum Cleaner",
    category: "Home & Garden",
    images_url:["https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/primary/371020-02.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=1920"],
    description: "Dyson V11 cordless vacuum cleaner, new condition with original packaging and manual.",
    price: 22000,
    quantity: 14,
    condition: "New",
    brand: "Dyson",
    model: "V11",
    dimensions_cm: { length: 130, width: 26, height: 26 },
    weight_kg: 3,
    material: "Plastic and metal",
    color: "Silver/Black",
    original_packaging: true,
    manual_included: true,
    working_condition: "Ready to use"
  },
  {
    title: "Adidas Soccer Ball",
    category: "Sporting Goods",
    images_url:["https://www.soccergarage.com/images/P/image-153.jpg"],
    description: "Adidas size 5 soccer ball with TPU synthetic cover, used but in excellent condition.",
    price: 1500,
    quantity: 12,
    condition: "Used - Like New",
    brand: "Adidas",
    model: "Standard Size 5",
    dimensions_cm: { diameter: 22 },
    weight_grams: 450,
    material: "TPU synthetic leather",
    color: "White/Red",
    original_packaging: false,
    manual_included: false,
    working_condition: "Fully functional"
  },
  {
    title: "Rolex Submariner Watch",
    category: "Jewelry & Watches",
    images_url:["https://diamondseast.com/cdn/shop/products/diamonds-east-intl-rolex-116610ln-rolex-oyster-perpetual-submariner-date-116610-ln-4820396933209_1024x1024.png?v=1623090423"],
    description: "Rolex Submariner stainless steel wristwatch, 40mm, refurbished, fully functional with sapphire crystal.",
    price: 500000,
    quantity: 12,
    condition: "Refurbished",
    brand: "Rolex",
    model: "Submariner 116610",
    dimensions_mm: { diameter: 40, thickness: 12 },
    weight_grams: 150,
    material: "Stainless steel",
    color: "Black",
    original_packaging: true,
    manual_included: true,
    working_condition: "Fully functional"
  },
  {
    title: "Levi's Men's Jeans",
    category: "Men's Clothing",
    images_url:["https://slimages.macysassets.com/is/image/MCY/products/9/optimized/19206779_fpx.tif?qlt=80,0&resMode=sharp2&op_usm=1.75,0.3,2,0&fmt=webp&wid=342&hei=417"],
    description: "This is a listing for pre-owned Levi's men's jeans. Classic straight fit, durable original denim, and distinctive Levi’s branding. Gently used with slight fading and no tears.",
    price: 1800,
    quantity: 1,
    condition: "Used",
    year_of_manufacture: null,
    brand: "Levi's",
    model: "501 Original",
    dimensions: { waist: 32, inseam: 34 },
    weight: 0.75,
    material: "100% Cotton Denim",
    color: "Blue",
    original_packaging: false,
    manual_included: false,
    working_condition: "Ready to wear"
  },
  {
    title: "IKEA Wooden Dining Table",
    category: "Home & Garden",
    images_url:["https://www.ikea.com/ext/ingkadam/m/62a030885c9f364/original/PE919457.jpg?f=xxs"],
    description: "180x90cm, 6-seater, light stains, legs sturdy, minimal wobble.",
    price: 12000,
    quantity: 1,
    condition: "Used - Good",
    year_of_manufacture: 1998,
    brand: "IKEA",
    model: "Model-381",
    dimensions: { length: 36.08, width: 61.47, height: 19.12 },
    weight: 3.97,
    material: "Solid pine or oak",
    color: "White",
    original_packaging: false,
    manual_included: true,
    working_condition: "Lightly used, good condition"
  }
  ,
  {
    title: "Fujifilm Instax Mini 11 Instant Camera",
    category: "Electronics",
    images_url: [
      "https://www.adorama.com/images/Large/FJIM11IW.jpg"
    ],
    description: "Fujifilm Instax Mini 11 instant camera for instant photo prints. Compact, stylish, and easy to use.",
    price: 6500,
    quantity: 12,
    condition: "Used - Like New",
    year_of_manufacture: 2020,
    brand: "Fujifilm",
    model: "Instax Mini 11",
    dimensions: { length: 11, width: 13, height: 7 },
    weight: 0.3,
    material: "Plastic body",
    color: "White",
    original_packaging: false,
    manual_included: true,
    working_condition: "Fully functional"
  },
  {
    title: "Jellyfish Night Light Projection Lamp",
    category: "Home & Garden",
    images_url: [
      "https://www.spacemanlight.com/wp-content/uploads/2024/09/jellyfish-ocean-projection-lamp02.jpg-768x768.webp"],
    description: "Cute jellyfish-themed night lamp that projects soothing patterns. Ideal for bedrooms or cozy corners.",
    price: 1200,
    quantity: 15,
    condition: "New",
    brand: "GlowCo",
    model: "JL-101",
    dimensions: { diameter: 10, height: 15 },
    weight: 0.5,
    material: "Silicone and plastic",
    color: "Blue",
    original_packaging: true,
    manual_included: true,
    working_condition: "New"
  },
  {
    title: "Camlin Colour Pen Pencil Set",
    category: "Office Supplies",
    images_url: [
      "https://rukminim2.flixcart.com/image/832/832/jmp79u80/art-set/t/t/4/colour-pen-pencil-set-of-12-camlin-original-imaf9gmnyxzfxnda.jpeg?q=70&crop=false"],
    description: "Set of 12 pastel-colored pen pencils with smooth flow. Perfect for journaling and office use.",
    price: 800,
    quantity: 25,
    condition: "New",
    brand: "Kikki.K",
    model: "Pastel Pen Pencil Set",
    dimensions: { length: 14 }, 
    weight: 0.1,
    material: "Plastic and ink",
    color: "Multiple pastel colors",
    original_packaging: true,
    manual_included: false,
    working_condition: "New"
  },
  {
    title: "Succulent Plant in Ceramic Pot",
    category: "Home Decor",
    images_url: [
      "https://i.pinimg.com/1200x/01/37/f2/0137f27860f6426e88064208dde7ad9e.jpg"],
    description: "Real succulent plant in white ceramic pot. Low maintenance and perfect for desk or room decor.",
    price: 900,
    quantity: 3,
    condition: "New",
    brand: "GreenHome",
    model: "Succulent A01",
    dimensions: { height: 15, diameter: 10 },
    weight: 0.4,
    material: "Ceramic pot, live succulent",
    color: "Green/White",
    original_packaging: true,
    manual_included: false,
    working_condition: "Live plant"
  },
  {
    title: "Adult Coloring Book with 50 Designs",
    category: "Books & Stationery",
    images_url: ["https://m.media-amazon.com/images/I/61QmuLr6XiL._AC_UY327_FMwebp_QL65_.jpg"],
    description: "A beautifully designed adult coloring book featuring 50 unique mandala and nature patterns.",
    price: 600,
    quantity: 30,
    condition: "New",
    brand: "ArtVibes",
    model: null,
    dimensions: { length: 21, width: 29.7, height: 1 },
    weight: 0.3,
    material: "Paper",
    color: "Multicolor cover",
    original_packaging: true,
    manual_included: false,
    working_condition: "New"
  }
]
module.exports = { data: products};

